SELECT
    CAST(YEAR AS INT) AS Year,
    CAST(MONTH AS INT) AS Month,
    CAST(DAY AS INT) AS Day,
    CAST(DAY_OF_WEEK AS INT) AS Day_Of_Week,
    CAST(LTRIM(RTRIM(AIRLINE)) AS VARCHAR(2)) AS Airline_Code,
    CAST(LTRIM(RTRIM(FLIGHT_NUMBER)) AS VARCHAR(10)) AS Flight_Number,
    {{ clean_tail_number('TAIL_NUMBER') }} AS Tail_Number,
    CAST(LTRIM(RTRIM(ORIGIN_AIRPORT)) AS VARCHAR(5)) AS Origin_Airport_Code,
    CAST(LTRIM(RTRIM(DESTINATION_AIRPORT)) AS VARCHAR(5)) AS Dest_Airport_Code,

    CAST(LEFT(RIGHT('0000' + CAST(CAST(SCHEDULED_DEPARTURE AS INT) AS VARCHAR), 4), 2) AS INT) AS Scheduled_Hour,
    CAST(RIGHT(RIGHT('0000' + CAST(CAST(SCHEDULED_DEPARTURE AS INT) AS VARCHAR), 4), 2) AS INT) AS Scheduled_Minute,

    CAST(DISTANCE AS INT) AS Distance,
    CAST(AIR_TIME AS DECIMAL(10, 2)) AS Air_Time,
    CAST(TAXI_OUT AS DECIMAL(10, 2)) AS Taxi_Out,
    CAST(TAXI_IN AS DECIMAL(10, 2)) AS Taxi_In,
    CAST(ARRIVAL_DELAY AS DECIMAL(10, 2)) AS Arrival_Delay,
    CAST(DEPARTURE_DELAY AS DECIMAL(10, 2)) AS Departure_Delay,

    CAST(CANCELLED AS BIT) AS Is_Cancelled,
    CAST(DIVERTED AS BIT) AS Is_Diverted,

    CAST(LTRIM(RTRIM(CANCELLATION_REASON)) AS VARCHAR(1)) AS Cancellation_Reason_Code,

    CAST(AIR_SYSTEM_DELAY AS DECIMAL(10, 2)) AS Air_System_Delay,
    CAST(SECURITY_DELAY AS DECIMAL(10, 2)) AS Security_Delay,
    CAST(AIRLINE_DELAY AS DECIMAL(10, 2)) AS Airline_Delay,
    CAST(LATE_AIRCRAFT_DELAY AS DECIMAL(10, 2)) AS Late_Aircraft_Delay,
    CAST(WEATHER_DELAY AS DECIMAL(10, 2)) AS Weather_Delay

FROM {{ source('raw_data', 'Raw_Flights') }}