SELECT
    CAST(LTRIM(RTRIM(IATA_CODE)) AS VARCHAR(3)) AS IATA_Code,
    CAST(LTRIM(RTRIM(AIRPORT)) AS VARCHAR(80)) AS Airport_Name,
    CAST(LTRIM(RTRIM(CITY)) AS VARCHAR(40)) AS City,
    CAST(LTRIM(RTRIM(STATE)) AS VARCHAR(2)) AS State,
    CAST(LTRIM(RTRIM(COUNTRY)) AS VARCHAR(3)) AS Country
FROM {{ source('raw_data', 'Raw_Airports') }}
WHERE IATA_CODE IS NOT NULL